<a href="https://colab.research.google.com/github/Ash-wika/Quick_ML_Rev/blob/main/tensors_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###**0D Tensor/Scalar**

In [2]:
a= np.array(4)

In [3]:
a

array(4)

In [4]:
a.ndim

0

###**1D Tensor/Vector**

No. of axis = rank
            = dimension of tensor

In [6]:
arr= np.array([1,2,3,4,5,6])

In [7]:
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
arr.ndim

1

1D called as vector but vector's dimesnion is 6D as there are 6 elements as 6 dimensions.

eg) [1,2] is a 1D tensor and vector. But the dimension of vector is 2.

=> If we keeping adding scalars to scalars it will form a vector.

###**2D Tensor/Matrices**

In [9]:
mat= np.array([[1,2,3,4],[5,7,6,8]])

In [10]:
mat

array([[1, 2, 3, 4],
       [5, 7, 6, 8]])

In [11]:
mat.ndim

2

###**ND Tensor**

In [16]:
vol = np.array([
    [
        [[1, 2, 3], [4, 5, 6]],
        [[7, 8, 9], [10, 11, 12]]
    ],
    [
        [[13, 14, 15], [16, 17, 18]],
        [[19, 20, 21], [22, 23, 24]]
    ]
])

In [17]:
vol

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

In [19]:
vol.ndim

4